#
#  STFL - The Structured Terminal Forms Language/Library
#  Copyright (C) 2006  Clifford Wolf <clifford@clifford.at>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

prefix = /usr/local

ifneq ($(shell spl-config --cflags 2>/dev/null),)
FOUND_SPL = 1
else
FOUND_SPL = 0
endif

ifneq ($(shell swig -help 2>/dev/null),)
FOUND_SWIG = 1
else
FOUND_SWIG = 0
endif

ifneq ($(shell perl -le 'print 1;' 2>/dev/null),)
FOUND_PERL = 1
else
FOUND_PERL = 0
endif

