#
#  STFL - The Structured Terminal Forms Language/Library
#  Copyright (C) 2006, 2007  Clifford Wolf <clifford@clifford.at>
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 3 of the License, or (at your option) any later version.
#  
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#  
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301 USA
#

export prefix = /usr/local
export DESTDIR = /

ifneq ($(shell spl-config --cflags 2>/dev/null),)
FOUND_SPL = 1
else
FOUND_SPL = 0
endif

ifneq ($(shell swig -help 2>/dev/null),)
FOUND_SWIG = 1
else
FOUND_SWIG = 0
endif

ifneq ($(shell perl -le 'print 1' 2>/dev/null),)
FOUND_PERL5 = 1
else
FOUND_PERL5 = 0
endif

ifneq ($(shell python -c 'print 1' 2>/dev/null),)
FOUND_PYTHON = 1
else
FOUND_PYTHON = 0
endif

ifneq ($(shell ruby -e 'puts 1' 2>/dev/null),)
FOUND_RUBY = 1
else
FOUND_RUBY = 0
endif

